---
title: "A test ting"
output: html_notebook
---


```{r}
library(ggplot2)
library(plyr)
library(dplyr)
library(gridExtra)
library(GGally) #for ggpairs
library(psych)
library(ggiraph)
library(ggiraphExtra)
```

```{r}
# IMPORTANT must import the data and apply these manipulations first. Otherwise the function will not work

covid_set <- read.csv('data/covid_data/covid_19_clean_complete.csv')
covid_set <- covid_set %>% mutate(date_str =  as.Date(as.POSIXct(Date, format="%m/%d/%y"))) %>% arrange(date_str)
covid_set

```

```{r}
# plotting deaths function
# USAGE: plot_deaths('Canada')
plot_deaths <- function(country) {
  country_set <- covid_set %>% filter(Country.Region == country)
  country_set.agg <- aggregate(select(country_set, Confirmed, Deaths, Recovered), by=country_set['date_str'], sum)
  deaths <- ggplot(country_set.agg, mapping = aes(date_str, Deaths)) + geom_line() + labs(title='Deaths', x='Date', y='Deaths')
  return(deaths)
}

# plotting confirmed function
# USAGE: plot_confirmed('Canada')
plot_confirmed <- function(country) {
  country_set <- covid_set %>% filter(Country.Region == country)
  country_set.agg <- aggregate(select(country_set, Confirmed, Deaths, Recovered), by=country_set['date_str'], sum)
  confirmed <- ggplot(country_set.agg, mapping = aes(date_str, Confirmed)) + geom_line() + labs(title='Confirmed Cases', x='Date', y='Cases')
  return(confirmed)
}

# plotting recovered function
# USAGE: plot_confirmed('Canada')
plot_recovered <- function(country) {
  country_set <- covid_set %>% filter(Country.Region == country)
  country_set.agg <- aggregate(select(country_set, Confirmed, Deaths, Recovered), by=country_set['date_str'], sum)
  recovered <- ggplot(country_set.agg, mapping = aes(date_str, Recovered)) + geom_line() + labs(title='Recovered', x='Date', y='Recovered')
  return(recovered)
}


plot_deaths('Canada')
plot_confirmed('Canada')
plot_recovered('Canada')
```

```{r}
# plotting change in deaths
# USAGE plot_change_deaths('Canada')
plot_change_deaths <- function(country) {
  country_set <- covid_set %>% filter(Country.Region == country)
  country_set.agg <- aggregate(select(country_set, Confirmed, Deaths, Recovered), by=country_set['date_str'], sum)
  country_set.new_by_week <- country_set.agg %>% mutate(new_deaths_by_week=Deaths - lag(Deaths, 7))
  plot <- ggplot(country_set.new_by_week, mapping = aes(Deaths, new_deaths_by_week)) + geom_line() + labs(title='Trajectory of Deaths', x='New Deaths (past week)', y='Total Deaths')
  return(plot)
}

# plotting change in cases
# USAGE plot_change_confirmed('Canada')
plot_change_confirmed <- function(country) {
  country_set <- covid_set %>% filter(Country.Region == country)
  country_set.agg <- aggregate(select(country_set, Confirmed, Deaths, Recovered), by=country_set['date_str'], sum)
  country_set.new_by_week <- country_set.agg %>% mutate(new_confirmed_by_week=Confirmed - lag(Confirmed, 7))
  plot <- ggplot(country_set.new_by_week, mapping = aes(Confirmed, new_confirmed_by_week)) + geom_line() + labs(title='Trajectory of Confirmed Cases', x='New Confirmed Cases (past week)', y='Total Confirmed Cases')
  return(plot)
}

plot_change_deaths('Canada')
plot_change_confirmed('Canada')
```
